services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .

  # db is the db folder
  db:
    build: db/.

    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: world

    restart: always
    ports:
      - "33060:3306"
