version: '3.8'
services:


  db:
    build: db/.

    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: world
    restart: always
    ports:
      - "33060:3306"

  app:
    build: .