name: A workflow for World Population App
on: push

jobs:
  build:
    name: World population action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup network
        run: |
          docker network create --driver bridge sem-CW
          docker pull mongo
          docker run -d --name mongo-dbserver --network sem-CW mongo
      - name: Build with Maven
        run: mvn package
      - name: Build
        run: docker build -t sem_CW .
      - name: Run image
        run: docker run --network sem-CW --name semcontainer sem_CW
      - name: view logs
        run: docker logs semcontainer